force-app/main/default/objects/MessagingSession/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Messaging Sessions</relationshipLabel>
    <relationshipName>Messaging_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/cookieId__c.field-meta.xml
<CustomField>
    <fullName>cookieId__c</fullName>
    <label>cookieId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Messaging_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/User_Email__c.field-meta.xml
<CustomField>
    <fullName>User_Email__c</fullName>
    <label>User Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/UsersId__c.field-meta.xml
<CustomField>
    <fullName>UsersId__c</fullName>
    <label>UsersId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GuestORLoggedInUserCheck.cls
public class GuestORLoggedInUserCheck {
	@InvocableMethod
    public static List<Response> getInputQuestion(List<Request> requests) {
        Request input = requests[0];
        String MSessionId= input.SessionId;
        System.debug('MSession'+MSessionId);
        List<Response> responses = new List<Response>(); 
        List<MessagingSession> messagingSessionList = [SELECT Id,cookieId__c,UsersId__c,User_Email__c,User__c,Contact__c,CreatedDate  FROM MessagingSession Where Id =: MSessionId];
        if(!messagingSessionList.isEmpty() && messagingSessionList[0].Contact__c == NULL){
            Response res = new Response();
            res.Prompt = false;
            responses.add(res);
        }else if(!messagingSessionList.isEmpty() && messagingSessionList[0].Contact__c != NULL){
            Response res = new Response();
            res.Prompt = true;
            responses.add(res);
        }
        
        System.debug('## responses = '+responses);  
        return responses;
    }
    
    public class Request {
        @InvocableVariable(required=true)
        public String SessionId; 
    }
    public class Response {
        @InvocableVariable
        public Boolean Prompt;
    }
}