force-app/main/default/objects/ShoeComparisonPopup__e/ShoeComparisonPopup__e.object-meta.xml
<CustomObject>
    <description>Event to popup of the Shoecomparison LWC</description>
    <label>ShoeComparisonPopup</label>
    <pluralLabel>ShoeComparisonPopups</pluralLabel>
</CustomObject>

force-app/main/default/objects/ShoeComparisonPopup__e/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <label>ContactId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShoeComparisonPopup__e/fields/IsModalOpen__c.field-meta.xml
<CustomField>
    <fullName>IsModalOpen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsModalOpen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShoeComparisonPopup__e/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <label>ProductId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DisplayShoeComparison.cls
public class DisplayShoeComparison {
 @InvocableMethod
    public static List<Response> getProductId(List<Request> requests) {
        System.debug('## experiences requests = '+requests);
        Request input = requests[0];
      
        String ProductId=input.ProductId; 
        String ContactId= input.ContactId;
        //event publish for loggenin user asking to compare
        If(ProductId!=null){
               System.debug('user_Question contains pet = '+ProductId);
            ShoeComparisonPopup__e  evt = New ShoeComparisonPopup__e();
            evt.IsModalOpen__c=true;
            evt.ProductId__c= ProductId;
            evt.ContactId__c= ContactId;
            
            //if(user_Question.containsIgnoreCase('suggest suitable shoes'))
            //evt.Input_Type__c='pet-allowed-hotel';
            Database.SaveResult result = EventBus.publish(evt);
            system.debug('event result'+ result);
               }
        
        else{
            system.debug('....');
        }
        
        System.debug('##publIsh platform event After ##');

        List<Response> responses = new List<Response>();
        Response res = new Response();
        System.debug('## no response ');
        res.Prompt = 'Published';
        responses.add(res);
        return responses;
    }
    
    // The variables in this class need to match the prompt template inputs,
    public class Request {
        @InvocableVariable(required=true)
        public String ProductId;
         @InvocableVariable(required=true)
        public String ContactId;
    }
    public class Response {
        @InvocableVariable
        public String Prompt;
    }
}