force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Average_Order__c.field-meta.xml
<CustomField>
    <fullName>Average_Order__c</fullName>
    <label>Average Order</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Average_order_value__c.field-meta.xml
<CustomField>
    <fullName>Average_order_value__c</fullName>
    <label>Average order value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Average_Quantity_per_Order__c.field-meta.xml
<CustomField>
    <fullName>Average_Quantity_per_Order__c</fullName>
    <description>Average Quantity per Order: Indicates purchasing habits (bulk vs. single items).</description>
    <inlineHelpText>Average Quantity per Order: Indicates purchasing habits (bulk vs. single items).</inlineHelpText>
    <label>Average Quantity per Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Average_time_between_orders__c.field-meta.xml
<CustomField>
    <fullName>Average_time_between_orders__c</fullName>
    <label>Average time between orders</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AveragePurchaseValue__c.field-meta.xml
<CustomField>
    <fullName>AveragePurchaseValue__c</fullName>
    <label>Average Purchase Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CategoryPreference__c.field-meta.xml
<CustomField>
    <fullName>CategoryPreference__c</fullName>
    <label>Category Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jackets &amp; Vests</fullName>
            </value>
            <value>
                <fullName>Tops</fullName>
            </value>
            <value>
                <fullName>Bottoms</fullName>
            </value>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Gear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ChannelPreference__c.field-meta.xml
<CustomField>
    <fullName>ChannelPreference__c</fullName>
    <label>Channel Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>n Store</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website &amp; App</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Churn_Score__c.field-meta.xml
<CustomField>
    <fullName>Churn_Score__c</fullName>
    <label>Churn Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/cookieId__c.field-meta.xml
<CustomField>
    <fullName>cookieId__c</fullName>
    <label>cookieId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Lifetime_Value_CLV__c.field-meta.xml
<CustomField>
    <fullName>Customer_Lifetime_Value_CLV__c</fullName>
    <label>Customer Lifetime Value (CLV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Satisfaction_CSAT__c.field-meta.xml
<CustomField>
    <fullName>Customer_Satisfaction_CSAT__c</fullName>
    <label>Customer Satisfaction (CSAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Days_since_the_last_order__c.field-meta.xml
<CustomField>
    <fullName>Days_since_the_last_order__c</fullName>
    <label>Days since the last order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Engagement_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Frequency__c</fullName>
    <label>Engagement Frequency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EngagementScore__c.field-meta.xml
<CustomField>
    <fullName>EngagementScore__c</fullName>
    <label>Engagement Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type> 
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Nonbinary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Income_Level__c.field-meta.xml
<CustomField>
    <fullName>Income_Level__c</fullName>
    <label>Income Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-5,00,000</fullName>
            </value>
            <value>
                <fullName>5,00,001-20,00,000</fullName>
            </value>
            <value>
                <fullName>20,00,001-50,00,000</fullName>
            </value>
            <value>
                <fullName>50,00,001 and above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Hiking</fullName>
            </value>
            <value>
                <fullName>Cycling</fullName>
            </value>
            <value>
                <fullName>Camping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Purchased_Product_Categories__c.field-meta.xml
<CustomField>
    <fullName>Last_Purchased_Product_Categories__c</fullName>
    <label>Last Purchased Product Categories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LifetimeValue__c.field-meta.xml
<CustomField>
    <fullName>LifetimeValue__c</fullName>
    <label>Lifetime Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Maximum_order_value__c.field-meta.xml
<CustomField>
    <fullName>Maximum_order_value__c</fullName>
    <label>Maximum order value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <description>Retail Club Membership Number</description>
    <label>Membership Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Most_Frequently_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Most_Frequently_Purchased__c</fullName>
    <label>Most Frequently Purchased Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OptInDate__c.field-meta.xml
<CustomField>
    <fullName>OptInDate__c</fullName>
    <label>Opt In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OptInSource__c.field-meta.xml
<CustomField>
    <fullName>OptInSource__c</fullName>
    <label>Opt In Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Store Pickup</fullName>
            </value>
            <value>
                <fullName>Website Form</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Mobile App Registration</fullName>
            </value>
            <value>
                <fullName>Social Media Ad/Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PhotoURL__c.field-meta.xml
<CustomField>
    <fullName>PhotoURL__c</fullName>
    <label>Photo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PreferredStore__c.field-meta.xml
<CustomField>
    <fullName>PreferredStore__c</fullName>
    <label>Preferred Store</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Propensity_to_purchase__c.field-meta.xml
<CustomField>
    <fullName>Propensity_to_purchase__c</fullName>
    <label>Propensity to purchase</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SubcategoryPreference__c.field-meta.xml
<CustomField>
    <fullName>SubcategoryPreference__c</fullName>
    <label>Subcategory Preference</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CategoryPreference__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insulated</fullName>
            </value>
            <value>
                <fullName>Rainwear</fullName>
            </value>
            <value>
                <fullName>Lightweight</fullName>
            </value>
            <value>
                <fullName>Windbreaker</fullName>
            </value>
            <value>
                <fullName>Shirts</fullName>
            </value>
            <value>
                <fullName>TShirts</fullName>
            </value>
            <value>
                <fullName>Sweatshirts</fullName>
            </value>
            <value>
                <fullName>Casual &amp; Hike</fullName>
            </value>
            <value>
                <fullName>Shorts</fullName>
            </value>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Boots</fullName>
            </value>
            <value>
                <fullName>Hiking</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Sandals</fullName>
            </value>
            <value>
                <fullName>Backpacks</fullName>
            </value>
            <value>
                <fullName>Gloves</fullName>
            </value>
            <value>
                <fullName>Hats</fullName>
            </value>
            <value>
                <fullName>Scarves</fullName>
            </value>
            <value>
                <fullName>Socks</fullName>
            </value>
            <value>
                <fullName>Sleeping Bags</fullName>
            </value>
            <value>
                <fullName>Tents</fullName>
            </value>
            <value>
                <fullName>Bikes</fullName>
            </value>
            <value>
                <fullName>Helmets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/AuthRequestTime__c.field-meta.xml
<CustomField>
    <fullName>AuthRequestTime__c</fullName>
    <description>Stores when authentication was requested, limiting the MessagingSession from being assigned identities outside of the directed window and allowing control of the timeframe during which external authentication is allowed.</description>
    <label>AuthRequestTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/AuthSessionId__c.field-meta.xml
<CustomField>
    <fullName>AuthSessionId__c</fullName>
    <description>Identifies if there’s an AuthSession currently linked to this MessagingSession. This indicates whether the messaging session is authenticated.</description>
    <label>AuthSessionId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Messaging Sessions</relationshipLabel>
    <relationshipName>Messaging_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/cookieId__c.field-meta.xml
<CustomField>
    <fullName>cookieId__c</fullName>
    <label>cookieId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Messaging_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/User_Email__c.field-meta.xml
<CustomField>
    <fullName>User_Email__c</fullName>
    <label>User Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/UsersId__c.field-meta.xml
<CustomField>
    <fullName>UsersId__c</fullName>
    <label>UsersId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ObjectAndFieldLevelPermissionRetail.cls
public class ObjectAndFieldLevelPermissionRetail {
    
    public static void assigndataCloudPermission(){
        
        String currentUserId = UserInfo.getUserId(); 
        // Query the Permission Set
        PermissionSet pSet = [SELECT Id, Name FROM PermissionSet WHERE Name ='B2BBuyer'  LIMIT 1]; 
        List<PermissionSetAssignment> perassignmnt=[SELECT Id, PermissionSetId, AssigneeId FROM PermissionSetAssignment WHERE AssigneeId =:currentUserId AND PermissionSetId =:pSet.Id];
        if(perassignmnt.isEmpty()){
            system.debug('perassignmnt'+perassignmnt);
            // Create the Permission Set Assignment
            PermissionSetAssignment permSetAssign = new PermissionSetAssignment(
                AssigneeId = currentUserId,
                PermissionSetId = pSet.Id
            );
            // Insert the Permission Set Assignment
            insert permSetAssign;
            system.debug('permSetAssign1'+permSetAssign);
        }
    }
    //Partner lead management- //Are we creating any Lead in Retail? //Done
    public static void assigndataPartnerLeadPermission(){
        String currentUserId = UserInfo.getUserId(); 
        // Query the Permission Set
        PermissionSet pSet = [SELECT Id FROM PermissionSet WHERE Name ='B2BBuyer' limit 1];
        List<PermissionSetAssignment> perassignmnt=[SELECT Id, PermissionSetId, AssigneeId FROM PermissionSetAssignment WHERE AssigneeId =:currentUserId AND PermissionSetId =:pSet.Id];
        if(perassignmnt.isEmpty()){
            system.debug('perassignmnt'+perassignmnt);
            PermissionSetAssignment permSetAssign = new PermissionSetAssignment(
                AssigneeId = currentUserId,
                PermissionSetId = pSet.Id
            );
            insert permSetAssign;
            system.debug('permSetAssign2'+permSetAssign); 
        }
    }
    
    //Assign Read Access to Custom Field to Data Cloud Salesforce Connector //Pending
    //@AuraEnabled
    public static void callinsertFieldLevelPermsssionMethod(){
        
        try {
            List<String> fieldsToUpdateforOpportunity = new List<String>{'Custom_Primary_Contact__c'}; 
                ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','Opportunity',fieldsToUpdateforOpportunity); 
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }
        
        try {
            List<String> fieldsToUpdateforMessagingSession = new List<String>{'UsersId__c','User_Email__c','User__c','Contact__c','cookieId__c','UserId__c','Contact__c','AuthRequestTime__c','AuthSessionId__c'}; 
                ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','MessagingSession',fieldsToUpdateforMessagingSession);
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }
        
        try {
            List<String> fieldsToUpdateforPromotion = new List<String>{'Discount__c'};   
                ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','Promotion',fieldsToUpdateforPromotion);
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }
        
        /*List<String> fieldsToUpdateforLead = new List<String>{'Intrested_In__c','CookieId__c'};   
        ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','Lead',fieldsToUpdateforLead); */
        
        //List<String> fieldsToUpdateforUser = new List<String>{'Account_Id_Formula__c'};   
        //  ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','User',fieldsToUpdateforUser);
        try {
            List<String> fieldsToUpdateforAccount = new List<String>{'PhotoURL__c'};   
                ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','Account',fieldsToUpdateforAccount);
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }
        
        try {
            List<String> fieldsToUpdateforContact = new List<String>{'LifetimeValue__c','EngagementScore__c','AveragePurchaseValue__c','Propensity_to_purchase__c',
                'CategoryPreference__c','ChannelPreference__c','SubcategoryPreference__c','PreferredStore__c','OptInDate__c','OptInSource__c','Interest__c',
                'Gender__c','Age__c','Average_Order__c','Average_order_value__c','Average_Quantity_per_Order__c','Average_time_between_orders__c','Engagement_Frequency__c',
                'Churn_Score__c','Days_since_the_last_order__c','Customer_Lifetime_Value_CLV__c','Customer_Satisfaction_CSAT__c','Income_Level__c','Last_Purchased_Product_Categories__c',
                'Location__c','Most_Frequently_Purchased__c','Membership_Number__c','Maximum_order_value__c','Net_Promoter_Score_NPS__c','Number_of_Complaint__c','Number_of_Product_Return__c',
                'Number_of_orders_period__c','Number_of_Unique_Products_Purchased__c','Payment_Method__c','Recency_Of_Purchase__c','Total_Amount_Spent_LTV__c',
                'Total_amount_spent_period__c','Ordered_In_Last_30_Days__c','Propensity_To_Churn__c'}; 
                    ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','Contact',fieldsToUpdateforContact); 
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }
        
        try {
            List<String> fieldsToUpdateforContactForRetail = new List<String>{'Propensity_To_Churn__c'}; 
                    ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('RetailPermissionSet','Contact',fieldsToUpdateforContactForRetail); 
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }
        
        try {
            List<String> fieldsToUpdateforProduct = new List<String>{'ManagedContentName__c','RT_Description__c','Total_Quantity__c','Recall_flag__c','Product_Catalog__c'};   
                ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','Product2',fieldsToUpdateforProduct);
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }
        
        try {
            List<String> fieldsToUpdateforProductAttribute = new List<String>{'Weight__c','Star__c','Ventilation__c','Size__c','Durability__c','Category__c'};   
                ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','ProductAttribute',fieldsToUpdateforProductAttribute);
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }
        try {
            List<String> fieldsToUpdateforProductItem = new List<String>{'next_stock_date__c', 'fulfilment_status_stock__c'};   
                ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','ProductItem',fieldsToUpdateforProductItem);
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }   
        
        try {
            List<String> fieldsToUpdateforOrder = new List<String>{'Contact__c','Product_Name__c'};  
                ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','Order',fieldsToUpdateforOrder);
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        }
        
        try {
            List<String> fieldsToUpdateforOrderItem = new List<String>{'ProductName__c'};  
                ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector','OrderItem',fieldsToUpdateforOrderItem);
        } catch (Exception ex) {
            System.debug('Permissions already exist or failed: ' + ex.getMessage());
        } 
        
        System.debug('Inside method callinsertFieldLevelPermsssionMethod'); 
        try {
            assigndataCloudPermission(); 
        } catch (Exception ex) {
            System.debug('Failed to assign Data Cloud permissions: ' + ex.getMessage());
        }
        
        try {
            assigndataPartnerLeadPermission();
        } catch (Exception ex) {
            System.debug('Failed to assign Partner Lead permissions: ' + ex.getMessage());
        }
        //assigndatavehicleassetfinance();
    }
    
    /*public static void assignPermission(String objectName, List<String> fields) {
try {
ObjectAndFieldLevelPermissionRetail.insertFieldLevelPermsssion('Data Cloud Salesforce Connector', objectName, fields);
} catch (Exception e) {
System.debug('Error assigning permission for ' + objectName + ': ' + e.getMessage());
}
} */
    
    public static void editAccesstoCustomer360(String permissionSetName, String objectName, List<String> fieldNames){
        PermissionSet permissionSetId = [Select Id from PermissionSet Where Label =: permissionSetName Limit 1];
        System.debug('## permissionSetId 360= '+permissionSetId);
        List<FieldPermissions> listOfFieldPermissions = new List<FieldPermissions>();
        for (String field : fieldNames) {
            FieldPermissions fieldPermission = new FieldPermissions();
            fieldPermission.Field = objectName + '.' + field;
            fieldPermission.SobjectType = objectName;
            fieldPermission.ParentId = permissionSetId.Id;
            fieldPermission.PermissionsEdit = true;
            fieldPermission.PermissionsRead = true;
            listOfFieldPermissions.add(fieldPermission);
        }
        if(!listOfFieldPermissions.isEmpty()){
            upsert listOfFieldPermissions;
            System.debug('## listOfFieldPermissions = '+listOfFieldPermissions);
        }
    }
    
    @future
    public static void assignCopyFieldPermission(){
        
        List<String> copyFieldAccess = new List<String>{'LifetimeValue__c','EngagementScore__c','AveragePurchaseValue__c'};  
            ObjectAndFieldLevelPermissionRetail.editAccesstoCustomer360('Customer 360 Data Platform Integration','Contact',copyFieldAccess);
    }
    
    //Pending
    public static void insertFieldLevelPermsssion(String permissionSetName, String objectName, List<String> fieldNames){
        PermissionSet permissionSetId = [Select Id from PermissionSet Where Label =: permissionSetName Limit 1];
        System.debug('## permissionSetId = '+permissionSetId);
        List<FieldPermissions> listOfFieldPermissions = new List<FieldPermissions>();
		List<FieldPermissions> fps= [SELECT Id,Field,ParentId,SobjectType,PermissionsEdit,PermissionsRead  FROM FieldPermissions Where ParentId =: permissionSetId.Id and SobjectType =:objectName and PermissionsRead = true];
        Map<String,Boolean> mapss = new Map<String,Boolean>();
		if(!fps.isEmpty()){            
            for(FieldPermissions fp : fps){
                mapss.put(fp.Field,fp.PermissionsRead);
            }
		}
        for (String field : fieldNames) {
			String obName = objectName + '.' + field;
			if((mapss.get(obName) != true && !mapss.isEmpty()) || mapss.isEmpty()){
				FieldPermissions fieldPermission = new FieldPermissions();
				fieldPermission.Field = objectName + '.' + field;
				fieldPermission.SobjectType = objectName;
				fieldPermission.ParentId = permissionSetId.Id;
				fieldPermission.PermissionsEdit = false;
				fieldPermission.PermissionsRead = true;
				listOfFieldPermissions.add(fieldPermission);//
			}            
        }
        if(!listOfFieldPermissions.isEmpty() && !Test.isrunningTest()){
            upsert listOfFieldPermissions;
            System.debug('## listOfFieldPermissions = '+listOfFieldPermissions);
        }
    }
    
    //Automation For automotive standard object , Assign read Access to retail object to Data Cloud Salesforce Connector //custom 360 is pending
    @AuraEnabled
    public static void assignPermissionSetForOutfitters(){
        try {
            String permissionSetName = 'sfdc_a360_sfcrm_data_extract'; 
            // Fetch the Permission Set ID
            PermissionSet permSet = [SELECT Id FROM PermissionSet WHERE Name = :permissionSetName LIMIT 1];
            system.debug('permSet'+permSet);
            if (permSet == null) {
                System.debug('Permission Set not found: ' + permissionSetName);
                return;
            }
            // List of Objects (Modify as needed)
            List<String> objectNames = new List<String>{
                'Order','Product2','ProductItem','Promotion','PromotionProduct','Pricebook2','pricebookEntry','OrderItem', 'ProductAttribute',
                    'ProductAttributeSet','ProductAttributeSetProduct','ProductCategoryProduct','CommerceEntitlementProduct','CommerceEntitlementPolicy',
                    'ProductCatalog','ProductCategory','Account','Contact','BuyerGroup','BuyerGroupMember', 'Lead','Opportunity', 'Location'};
                        system.debug('Object Name'+objectNames);
            // Fetch existing permissions for these objects under this Permission Set
            Map<String, ObjectPermissions> existingPerms = new Map<String, ObjectPermissions>();
            for (ObjectPermissions op : [SELECT Id, SObjectType 
                                         FROM ObjectPermissions 
                                         WHERE ParentId = :permSet.Id 
                                         AND SObjectType IN :objectNames]) {
                                             existingPerms.put(op.SObjectType, op);
                                         }
            // Prepare ObjectPermissions records to insert
            List<ObjectPermissions> objPermsToInsert = new List<ObjectPermissions>();
            for (String objectName : objectNames) {
                if (!existingPerms.containsKey(objectName)) {
                    ObjectPermissions objPerm = new ObjectPermissions(
                        ParentId = permSet.Id,
                        SObjectType = objectName,
                        PermissionsRead = true,
                        PermissionsViewAllRecords = true
                    );
                    System.debug('Object to insert'+objPerm);
                    objPermsToInsert.add(objPerm);
                } else {
                    System.debug('Skipping ' + objectName + ' - Permission already exists.');
                }
            } 
            
            // Insert only new permissions
            if (!objPermsToInsert.isEmpty()) {
                try {
                    insert objPermsToInsert;
                    System.debug('Object Permissions Assigned Successfully!');
                } catch (Exception e) {
                    System.debug('Error Assigning Permissions: ' + e.getMessage());
                }
            } else {
                System.debug('No new permissions needed - Everything is already assigned.');
            }
            
            // Query permiaaion set 
            String currentUserId = UserInfo.getUserId(); 
            List<PermissionSet> retailPS = [Select id, Name from PermissionSet where Name = 'RetailPermissionSet' limit 1];    
            List<PermissionSetAssignment> loyaltyPSetAssignmnt =  [SELECT Id,AssigneeId,PermissionSetId FROM PermissionSetAssignment WHERE  PermissionSetId =:retailPS[0].Id AND AssigneeId =:currentUserId LIMIT 1];
            
            system.debug('retail PS'+retailPS);
            
            if(!retailPS.isEmpty() && loyaltyPSetAssignmnt.isEmpty()){
                PermissionSetAssignment retailAdmin = new PermissionSetAssignment(
                    AssigneeId = currentUserId,
                    PermissionSetId = retailPS[0].Id
                );
                // Insert the Permission Set Assignment
                insert retailAdmin;
            }   
        } catch (Exception e) {
            System.debug('Error occurred:' + e.getMessage());
            throw new AuraHandledException('An Error Occured:' +e.getMessage());
            
        }
    }
    
    //Automation for Create an AgentUser
    @AuraEnabled
    public static void botUserForServiceAgent(){
        //to create Agent User
        try {
            String emailAddress = UserInfo.getUserEmail();
            String userName;
            if (Test.isRunningTest()){
                userName= UserInfo.getUserName() +'.'+'Outfittersbotuser1';
            }
            else{
                username= UserInfo.getUserName() +'.'+'agentuser1';
                system.debug('username'+username);
            }
            
            List<UserLicense> ul=[SELECT Id, Status, MasterLabel, Name FROM UserLicense Where Name='Einstein Agent' LIMIT 1];
            system.debug('ul'+ul);
            if(!ul.isEmpty()){
                Profile prof = [SELECT Id, UserLicenseId FROM Profile WHERE Name='Einstein Agent User' AND UserLicenseId =: ul[0].Id limit 1];
                system.debug('prof'+prof);
                if(prof !=null){
                    User usr = new user();
                    usr.FirstName = 'Agent';
                    usr.LastName='User';
                    usr.Email = emailAddress;
                    usr.Alias = 'agtuser';
                    usr.Username = userName;
                    usr.LocaleSidKey = 'en_US';
                    usr.TimeZoneSidKey = 'GMT';
                    usr.ProfileID = prof.id;
                    usr.LanguageLocaleKey = 'en_US';
                    usr.EmailEncodingKey = 'UTF-8';
                    insert usr;
                    system.debug('insert user'+usr);
                }
                map<string,string> mapOfPSwithAgentUser = new map<string,string>();
                
                User agentUser = [SELECT Id FROM User WHERE FirstName='Agent' AND LastName ='User' LIMIT 1];
                List<PermissionSet> permSet = [SELECT Id,Name FROM PermissionSet Where Name IN ('AgentforceServiceAgentUser', 'Outfitters_Service_Agent', 'CopilotSalesforceUser','GenieUserEnhancedSecurity')];//3
                List<PermissionSetLicense> pslicense= [SELECT DeveloperName,Id,MasterLabel FROM PermissionSetLicense Where MasterLabel ='Agentforce Service Agent User' LIMIT 1];
                List<PermissionSetAssignment> listOfPSA = [SELECT Id,AssigneeId,PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId=:agentUser.Id and PermissionSetId IN:permSet];
                if(listOfPSA.size()>0){
                    for(PermissionSetAssignment psaRec:listOfPSA){
                        System.debug('psaRec -->'+psaRec);
                        mapOfPSwithAgentUser.put(psaRec.PermissionSetId,psaRec.AssigneeId);
                    } 
                }
                List<PermissionSetLicenseAssign> listOfPSLwithAgent = [SELECT id,AssigneeId,PermissionSetLicenseId FROM PermissionSetLicenseAssign 
                                                                       WHERE AssigneeId=:agentUser.id AND PermissionSetLicenseId=:pslicense[0].id];
                
                
                //Assign 'Agentforce Service Agent User' Permission Set License to Agent User
                
                if(listOfPSLwithAgent.isEmpty() && !pslicense.isEmpty()){
                    
                    PermissionSetLicenseAssign pslicnseAssignee = New PermissionSetLicenseAssign();
                    pslicnseAssignee.AssigneeId=agentUser.Id;
                    pslicnseAssignee.PermissionSetLicenseId =pslicense[0].Id;
                    if(!Test.isRunningTest()){
                        Insert pslicnseAssignee;
                        System.debug('pslicnseAssignee -->'+pslicnseAssignee);
                    }
                    
                }
                List<PermissionSetAssignment> psToAssign = new List<PermissionSetAssignment>();
                if(!permSet.isEmpty()){
                    for(PermissionSet ps : permSet){
                        if(!mapOfPSwithAgentUser.containskey(ps.id)){                           
                            PermissionSetAssignment permissionSetAssignment = new PermissionSetAssignment();
                            permissionSetAssignment.PermissionSetId = ps.Id;
                            permissionSetAssignment.AssigneeId = agentUser.Id;
                            psToAssign.add(permissionSetAssignment);
                        }
                        
                    }
                    
                    if(!psToAssign.isEmpty() && !Test.isRunningTest()){
                        insert psToAssign;
                    }       
                }
            }
        }   catch (Exception e) {
            System.debug('Error occurred:' + e.getMessage());
            throw new AuraHandledException('An Error Occured:' +e.getMessage());
        }
        
    }
    
    
    //Automation for assigning Permission Set to Integration User
    @AuraEnabled
    public static void assignIntegrationPermSet(){
        String permissionSetName='sfdc_a360';
        PermissionSet permSet = [SELECT Id FROM PermissionSet WHERE Name = :permissionSetName LIMIT 1];
        System.debug('Permission Set After Query ' + permSet);
        if (permSet == null) {
            System.debug('Permission Set not found: ' + permissionSetName);
            return;
        }
        String objectName = 'Contact';
        String objectAccount = 'Account';
        
        List<ObjectPermissions> existingPermAcc = [SELECT Id, SObjectType 
                                                   FROM ObjectPermissions 
                                                   WHERE ParentId = :permSet.Id 
                                                   AND SObjectType= :objectAccount  LIMIT 1 ];
        System.debug('Existing Permission Set Check'+existingPermAcc);
        if(existingPermAcc!=null){
            System.debug('Contact Permissions already exist-Skipping');
            delete existingPermAcc;
        }
        List<ObjectPermissions> existingPerm = [SELECT Id, SObjectType 
                                                FROM ObjectPermissions 
                                                WHERE ParentId = :permSet.Id 
                                                AND SObjectType= :objectName LIMIT 1 ];
        System.debug('Existing Permission Set Check'+existingPerm);
        if(existingPerm!=null){
            System.debug('Contact Permissions already exist-Skipping');
            delete existingPerm;
        }
        ObjectPermissions contactPerm = new ObjectPermissions(
            ParentId = permSet.Id,
            SObjectType = objectName,
            PermissionsDelete = true,
            PermissionsEdit=true,
            PermissionsModifyAllRecords=true,
            PermissionsRead = true,
            PermissionsViewAllRecords=true
        );
        
        ObjectPermissions accPerm = new ObjectPermissions(
            ParentId = permSet.Id,
            SObjectType = objectAccount,
            PermissionsDelete = true,
            PermissionsEdit=true,
            PermissionsModifyAllRecords=true,
            PermissionsRead = true,
            PermissionsViewAllRecords=true
        );
        try{
            insert contactPerm;
            insert accPerm;
            
            system.debug('Contact object Permission Set Assigned Successfully');
        }catch(Exception e){
            System.debug('Error Assigning Permissions'+e.getMessage());
        }
    }
    //Create Community User //Done
    public static void createCustomerCommunityUser(){
        try {
            List<Contact> contactRecord = [SELECT Id, FirstName, Name, LastName, Email FROM Contact WHERE Name = 'Mark Smith' AND Email='msmith@yopmail.com' LIMIT 1];
            List<UserLicense> ul=[SELECT Id, Status, MasterLabel, Name FROM UserLicense Where Name='Customer Community Plus' LIMIT 1];
            List<Profile> profList = [SELECT Id, UserLicenseId FROM Profile Where Name = 'Outfitters Profile' LIMIT 1];
            
            if (!contactRecord.isEmpty() && !profList.isEmpty()) {
                String emailAddress = contactRecord[0].Email;
                System.debug('community user email ->'+emailAddress);
                String userName = emailAddress +'.'+'customerUser'+System.now().format('ddMMyyyyHHmmss').substring(8,14);
                
                User usr = new user();
                usr.FirstName = 'Mark';
                usr.LastName='smith';
                usr.Email = emailAddress;
                usr.Alias = 'msmith';
                usr.Username = userName;
                usr.LocaleSidKey = 'en_US';
                usr.TimeZoneSidKey = 'GMT';
                usr.ProfileID = profList[0].Id;
                usr.LanguageLocaleKey = 'en_US';
                usr.EmailEncodingKey = 'UTF-8';
                usr.ContactId = contactRecord[0].Id;
                //usr.IsPortalEnabled = true;
                insert usr;
                System.debug(usr + 'usr');
                
                User userRecord = [SELECT Id, IsPortalEnabled, ProfileId FROM User WHERE ContactId = :contactRecord[0].Id LIMIT 1]; 
                If(userRecord != NULL){
                    userRecord.IsPortalEnabled = true;
                    UPDATE userRecord;
                }
                List<PermissionSet> pSet = [SELECT Id FROM PermissionSet WHERE Name ='Commerce_Shopper' LIMIT 1]; //Check
                
                //List<PermissionSet> pSet = [SELECT Id FROM PermissionSet WHERE Name ='SDO_Community_Customer_Community_Plus_Permissions' LIMIT 1];//Need to check
                System.debug('Retail perm set'+pSet);
                // Create the Permission Set Assignment
                if(!pSet.isEmpty()){
                    System.debug('Retail perm set 333'+pSet);
                    PermissionSetAssignment permSetAssign = new PermissionSetAssignment(
                        AssigneeId = usr.Id,
                        PermissionSetId = pSet[0].Id
                    );
                    // Insert the Permission Set Assignment
                    insert permSetAssign;
                }
                List<PermissionSet> permSet = [SELECT Id FROM PermissionSet WHERE Name ='B2BBuyer' LIMIT 1]; //Need to check
                
                if(!permSet.isEmpty()){
                    // Create the Permission Set Assignment
                    PermissionSetAssignment permSetAssign = new PermissionSetAssignment(
                        AssigneeId = usr.Id,
                        PermissionSetId = permSet[0].Id
                    );
                    // Insert the Permission Set Assignment
                    Insert permSetAssign;
                }                
            }
        } catch (Exception e) {
            System.debug('Exception: ' + e.getMessage());
        }
        
    }
    
    
    //assign account buyer group 
    @future
    public static void assignCommunityUserToBuyerGroup(){
        List<BuyerGroup> buyerGroups = [SELECT Id, Name FROM BuyerGroup WHERE Name IN ('Outfitters Authenticated users', 'Outfitters Buyer Group')]; //Outfitters Authenticated users / Outfitters Buyer Group
        system.debug('buyerGroups'+buyerGroups);
        List<Contact> con = [SELECT Id,AccountId,Email FROM Contact WHERE Email ='dmacintosh@yopmail.com'];
        system.debug('con'+con[0].AccountId);
        if(!con.isEmpty() && buyerGroups != null){
            /*BuyerGroupMember buyerGroupMember = new BuyerGroupMember(BuyerId = con[0].AccountId,BuyerGroupId= buyerGroupId);
insert buyerGroupMember;
} */
            List<BuyerGroupMember> buyerGroupMembers = new List<BuyerGroupMember>();
            
            for (BuyerGroup bg : buyerGroups) {
                BuyerGroupMember buyerGroupMember = new BuyerGroupMember(
                    BuyerId = con[0].AccountId,
                    BuyerGroupId = bg.Id
                );
                buyerGroupMembers.add(buyerGroupMember);
            }
            insert buyerGroupMembers;
        }
    } 
    
    public static void assignPersonalizationPermissionSet() {
        try {
            String permissionSetName = 'Personalization'; 
            List<PermissionSet> permSetList = [SELECT Id FROM PermissionSet WHERE Name = :permissionSetName LIMIT 1];
            if (permSetList.isEmpty()) {
                System.debug('Permission Set not found: ' + permissionSetName);
                return;
            }
            PermissionSet permSet = permSetList[0];
            
            String currentUserId = UserInfo.getUserId();
            List<PermissionSetAssignment> existingAssignments = [
                SELECT Id FROM PermissionSetAssignment 
                WHERE AssigneeId = :currentUserId AND PermissionSetId = :permSet.Id
            ];
            
            if (existingAssignments.isEmpty()) {
                PermissionSetAssignment psa = new PermissionSetAssignment(
                    AssigneeId = currentUserId,
                    PermissionSetId = permSet.Id
                );
                insert psa;
                System.debug('Permission set "Personalization" assigned to current user.');
            } else {
                System.debug('Current user already has the "Personalization" permission set.');
            }
            
        } catch (Exception e) {
            System.debug('Error assigning personalization permissions: ' + e.getMessage());
            throw new AuraHandledException('An Error Occurred: ' + e.getMessage());
        }
    }
    
}